# Generated by Django 6.0.5 on 2026-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
